### ISSUE TITLE
Movidius support?

### ISSUE THREAD

**Issue by davenso** [opencv/dldt#13]
Hi, In the repo, I don't see code for Movidius. Is Movidius device supported?

**Comment by tedchina** [comment]
Movidius is certainly supported.
You can specify the device parameter as below, where MYRIAD stands for Movidius VPU.
`-d "<device>"           Specify the target device to infer on; CPU, GPU, FPGA or MYRIAD is acceptable. Sample will look for a suitable plugin for device spec`

**Comment by moslex** [comment]
Hello, @davenso 
Myriad plugin is not a part of open source distribution yet. Please, read this FAQ: https://01.org/openvinooolkit/faq for more details.

Please, use Intel(R) distribution of OpenVINO(tm) toolkit to run inference on Myriad: https://software.intel.com/en-us/openvino-toolkit

**Comment by nickoala** [comment]
I feel disappointed that:

1. Intel distribution of OpenVINO toolkit does not support ARM hardware (meaning I cannot install it on Raspberry Pi)
2. Myriad plugin is not included in the open source distribution (meaning I cannot build it myself for Raspberry Pi to use a Neural Compute Stick 2)

I hope support for ARM / Raspberry Pi is in the work. Otherwise, the NCS2 would be pretty useless for edge devices.

**Comment by tedchina** [comment]
@nickoala In #3 it was said Raspberry Pi is planned to be supported (as a host instead of accelerator).
