### ISSUE TITLE
reverse_input_channels addition to Calibration Tool model.yml file

### ISSUE THREAD

**Issue by agungor2** [opencv/dldt#181]
I have a Resnet50 trained model on 37 class problem and I'm trying to run Calibration tool. The problem is that if I don't define reverse_input_channels in the model optimizer, the accuracy drops drastically. I am wondering if I can define it in a way that the Calibration tool could accept it. Here is my model.yml file: 
models:
  - name: resnet50
    launchers:
      - framework: dlsdk
        device: CPU
        tf_model: all_layers.rn50.pb
        adapter: classification
        mo_params:
            data_type: FP32
            input_shape: "(128, 224, 224, 3)"
        datasets:
            - name : breeds_pictures_val 

If I add  reverse_input_channels: True to arguments below mo_params it doesn't accept it. Any suggestions?

**Comment by shubha-ramani** [comment]
Dear @agungor2 

There is a sample_config.yml which can be found in C:\Program Files (x86)\IntelSWTools\openvino_2019.1.148\python\python3.5\openvino\tools\accuracy_checker\sample . Unfortunately I'm not seeing it in the dldt github.

If the model is trained in BGR, you normally don’t need to do - -reverse-input-channels.  Why do we need - - reverse-input-channels ? Because OpenCV reads images in BGR format while models are normally trained in RGB format.

Within sample_config.yml,  you will find the following:

Note this section: # list of preprocessing, applied to each image during validation
        # order of entries matters
        preprocessing:
            # resize input image to topology input size
            # you may specify size to which image should be resized
            # via dst_width, dst_height fields
          - type: resize
            size: 32
            # topology is trained on RGB images, but OpenCV reads in BGR
            # thence it must be converted to RGB
          - type: bgr_to_rgb
            # dataset mean and standard deviation
          - type: normalization
            # you may specify precomputed statistics manually or use precomputed values, such as ImageNet as well
            mean: (125.307, 122.961, 113.8575)
            std: (51.5865, 50.847, 51.255)


You don’t have to use that bgr_to_rgb item. For instance, look at this sample yml, the bgr_to_rgb is missing altogether:

[https://github.com/opencv/dldt/blob/2019/tools/accuracy_checker/configs/person-reidentification-retail-0079.yml](https://github.com/opencv/dldt/blob/2019/tools/accuracy_checker/configs/person-reidentification-retail-0079.yml)

You didn’t mention which part of the calibration toolset is dropping accuracy, so I’m assuming it’s accuracy checker. Well if your model was trained in RGB and you’re using OpenCV (which the majority of our samples and tools do actually) in the backend you must specify - - reverse_input_channels as I mentioned earlier. Our calibration tools are (likely) using OpenCV to process images, so this is why - -reverse_input_channels is required.

Please take a look at the sample configs shown in the above URL.

You may wish to leave off - - reverse_input_channels in your MO command and instead let your config.yml address it as above – that is, if you trained your model in RGB. 

Hope it helps,

Thanks,

Shubha

**Comment by agungor2** [comment]
Hey Shubha, 

Thanks for the help. Here is how I came around this issue: 

adapter: classification
        mo_params:
            data_type: FP32
            input_shape: "(128, 224, 224, 3)"
            mean_values: "(123,117, 104)"
        mo_flags:
          - reverse_input_channels

It's possible to assert mo_flags and within define reverse_input_channels. I was also having issues with identifying the right preprocessing steps for Resnet50 model. That's the reason why we have mean_values set to the specific values. 

Thanks, 
Mecit
