### ISSUE TITLE
i found that the op conv2d_transpose takes lots of time when i use openvino 2019

### ISSUE THREAD

**Issue by jlygit** [opencv/dldt#184]
hello,
the op conv2d_transpose takes lots of time when i use  openvino 2019.

![image](https://user-images.githubusercontent.com/10195989/59744092-6814db80-92a4-11e9-9779-b547f5a773b5.png)

the follow shows the time  when i use  openvino 2018.
![image](https://user-images.githubusercontent.com/10195989/59744212-a0b4b500-92a4-11e9-8a33-035d6d9103f5.png)

**Comment by ilyachur** [comment]
Hi @jlygit,

Yes your deconvolution layer has a bad performance because it is executed in the reference implementation.
As you can see in the OpenVINO 2018 gemm primitive was executed for this deconvolution.

It looks like a bug. Could you please send the parameters of this deconvolution layer (strides, kernels and etc.)? We should investigate why CPU plugin cannot execute this layer in the gemm implementation.

**Comment by xiuxin121** [comment]
we have same problem

**Comment by shubha-ramani** [comment]
Dear @jlygit 
Please if you could send the parameters which @ilyachur is asking for and also supply a small sample which demonstrates this issue (as a *.zip file) I'd be happy to file a bug on your behalf.

Also @xiuxin121 and @jlygit 
Thanks for your patience !

Shubha

**Comment by jlygit** [comment]
@shubha-ramani @ilyachur 

hi, the model i used is as follow,
[model.zip](https://github.com/opencv/dldt/files/3339004/model.zip)
