### ISSUE TITLE
Why EXCLUDE_FROM_ALL of extension?

### ISSUE THREAD

**Issue by LamyZee** [opencv/dldt#221]
A question about inference-engine/src/CMakeLists.txt, line 40.
`
add_subdirectory(extension EXCLUDE_FROM_ALL)    
add_library(IE::ie_cpu_extension ALIAS ie_cpu_extension)
`
Why not build extension with inference-engine, have some reason?

**Comment by shubha-ramani** [comment]
Dear @LamyZee,
You ask an excellent question. The reason it is done this way is for hardware abstraction. Keep in mind today, OpenVino works on FPGA, CPU, GPU VPU and who knows what the future holds. Inference Engine is "OneAPI" and works seamlessly across all the hardware, each of which requires a separate and unique plugin containing the low level hardware primitives and optimizations.  So maybe the next question is, why not put CPU extensions in the CPU Plugin ? All the CPU extensions code is located [here](https://github.com/opencv/dldt/tree/2019/inference-engine/src/extension) . Well, it's because CPU extensions do not belong in the CPU Plugin really. What if the user wants to add a currently unsupported layer (i.e. custom layers) and add a new CPU extension ? There is a super seamless and easy way to do that, ergo the CPU Extensions Library. We allow GPU custom layers also and in R2, VPU Custom Layers too (Preview Mode for VPU in R2) - these are realized via OpenCL.

**Comment by LamyZee** [comment]
Dear @shubha-ramani ,
Thanks for your reply, it's very useful to me.
In fact, I want to build a project base on OpenVino, I know what device I will use. So, I can precompile those extensions, my teammate just use it.

Best,
LamyZee
