### ISSUE TITLE
Converting a TensorFlow* Model

### ISSUE THREAD

**Issue by DucLong06** [opencv/dldt#419]
I want to convert my 1 tensorflow model to IR currently I am following the instructions here:
https://docs.openvinotoolkit.org/latest/_docs_MO_DG_prepare_model_convert_model_Convert_Model_From_TensorFlow.html

The model I use is meta graph and win 10 ver 1903
My model clone : 
https://github.com/ZJULearning/pixel_link

I am trying to freeze a flow pattern

In tenorflow, training from scratch is created after 4 files:

1. model.ckpt-38055.data-00000-of-00001
2. model.ckpt-38055.index
3. model.ckpt-38055.meta
4. checkpoint

I would like to convert them (or only the needed ones) into one file 

> graph.pb

 I use src :
```
import tensorflow as tf

meta_path = 'model.ckpt-454501.meta'  # Your .meta file
# output_node_names = ['output:0']    # Output nodes

with tf.Session() as sess:
    # Restore the graph
    saver = tf.train.import_meta_graph(meta_path)

    # Load weights
    saver.restore(sess, tf.train.latest_checkpoint('E:\OpenVino\SANGKV'))

    output_node_names = [n.name for n in tf.get_default_graph().as_graph_def().node]

    # Freeze the graph
    frozen_graph_def = tf.graph_util.convert_variables_to_constants(
        sess,
        sess.graph_def,
        output_node_names)

    # Save the frozen graph
    with open('output_graph.pb', 'wb') as f:
        f.write(frozen_graph_def.SerializeToString())

```

I encountered an error :
```
WARNING:tensorflow:The saved meta_graph is possibly from an older release:
'local_variables' collection should be of type 'byte_list', but instead is of type 'node_list'.
WARNING:tensorflow:The saved meta_graph is possibly from an older release:
'model_variables' collection should be of type 'byte_list', but instead is of type 'node_list'.
Traceback (most recent call last):
  File "freeze_graph1.py", line 11, in <module>
    saver.restore(sess, tf.train.latest_checkpoint('E:\OpenVino\pixel_link_pb'))
  File "C:\Users\Lerror\Anaconda3\lib\site-packages\tensorflow\python\training\saver.py", line 1742, in latest_checkpoint
    if file_io.get_matching_files(v2_path) or file_io.get_matching_files(
  File "C:\Users\Lerror\Anaconda3\lib\site-packages\tensorflow\python\lib\io\file_io.py", line 333, in get_matching_files
    for single_filename in filename
  File "C:\Users\Lerror\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: FindFirstFile failed for: /home/dengdan/models/pixel_link/well_trained_models/ic15/conv3_3 : The system cannot find the path specified.
; No such process
```

Hope you can help me

thank you

**Comment by leavim** [comment]
Hi @DucLong06 ,

In order to get the resulting .pb files I think its required to know the output node name(s) of the model. You can try to use [Netron ](https://github.com/lutzroeder/netron)or some other tool/script of your choice to figure the output names out. You can try posting your question in TF git and check if they have any suggestions.

There are a couple of text-detection models available in the OMZ that are based on the PixelLink architecture, take a look at the [documentation](https://docs.openvinotoolkit.org/latest/usergroup8.html) for more info. There is a demo app ([Text Detection C++ Demo](https://docs.openvinotoolkit.org/latest/_demos_text_detection_demo_README.html)) available in the toolkit for your to try.

Regards,
Luis

**Comment by DucLong06** [comment]
hi @leavim 
thanks kiu so much
